#Install and configure coc
- name: Install nodejs
  become: true
  package:
      name: "{{item}}" 
      state: latest
      update_cache: yes
  loop:
      - nodejs
      - npm

- name: Install COC
  git:
      repo: https://github.com/neoclide/coc.nvim.git
      dest: "{{plugins_dir}}/coc.nvim"
      version: release

