---
# tasks file for NvimConfiguration

- name: Installing packages for Debian_based
  include_tasks:
      file: debian_based.yml
  when: ansible_os_family == "Debian"


- name: Installing packages for Arch_based
  include_tasks:
      file: arch_based.yml
  when: ansible_os_family == "Archlinux"


- name: Installing packages for RedHat_based
  include_tasks:
      file: redhat_based.yml
  when: ansible_os_family == "RedHat"


- name: Creating Nvim config directory
  ansible.builtin.file:
      dest: "/home/{{user_name}}/.config/nvim"
      state: directory
      mode: 0767
  become_user: "{{user_name}}"


- name: Creating Nvim config file
  become_user: "{{user_name}}"
  ansible.builtin.copy: 
        dest: "/home/{{user_name}}/.config/nvim/init.vim"
        src: "{{ lookup('env', 'HOME') }}/.config/nvim/init.vim"
        mode: 0767
        backup: yes


- name: Include Nvim plugins installation
  include_tasks:
      file: Nvim_plugins.yml
      apply:
          tags: CocInstall

- name: Include Coc installation
  include_tasks:
      file: coc_config.yml
      apply:
          tags: CocInstall

