---
# tasks file for NvimConfiguration
- name: Install NeoVim
  become: true
  ansible.builtin.apt:
      force_apt_get: yes
      update_cache: yes
      name:
          - neovim
      state: latest


- name: Creating Nvim config directory
  ansible.builtin.file:
      dest: "{{ansible_user_dir}}/.config/nvim"
      state: directory
      mode: 0767


- name: Setting host HOME variable
  ansible.builtin.set_fact:
        host_home_dir: "{{ lookup('env', 'HOME')}}"


- name: Creating Nvim config file
  ansible.builtin.copy: 
        dest: "{{ansible_env.HOME}}/.config/nvim/init.vim"
        src: "{{host_home_dir}}/.config/nvim/init.vim"
        mode: 0767
        backup: yes




- name: Include Coc installation
  include_tasks:
      file: coc_config.yml
      apply:
          tags: CocInstall
