#Tasks for install Nvim plugins

  #Downloading vim-plug file
- name: Install Vim-plug
  ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: "{{ansible_user_dir}}/.local/share/nvim/site/autoload/plug.vim"


- name: Getting init.vim file
  ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/Piii-thagorus/dotfiles/master/.config/nvim/init.vim
      dest: "{{ansible_user_dir}}/.config/nvim/init.vim"
  

- name: Vim-airlines
  git: 
    repo: https://github.com/bling/vim-airline.git 
    dest: "{{ plugins_dir }}/vim-airline" 


- name: UltiSnips
  git: 
    repo: https://github.com/SirVer/ultisnips.git 
    dest: "{{plugins_dir}}/ultisnips"


- name: Snippets
  git: 
    repo: https://github.com/honza/vim-snippets.git 
    dest: "{{ plugins_dir }}/vim-snippets"


- name: NerdTree
  git: 
    repo: https://github.com/scrooloose/nerdtree 
    dest: "{{ plugins_dir }}/nerdtree"


- name: Tagbar
  git: 
    repo: https://github.com/majutsushi/tagbar.git 
    dest: "{{ plugins_dir }}/tagbar"

