#Tasks for install Nvim plugins

- name: Make Vim-plug directory
  ansible.builtin.file:
    path: "/home/{{user_name}}/.local/share/nvim/site/autoload"
    state: directory
    owner: "{{user_name}}"
    mode: 0767


- name: Make Vim-plug file
  ansible.builtin.file:
    path: "/home/{{user_name}}/.local/share//nvim/site/autoload/plug.vim"
    state: touch
    mode: 0767


- name: Install Vim-plug
  ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      force: yes
      dest: "/home/{{user_name}}/.local/share//nvim/site/autoload/plug.vim"


- name: Getting init.vim file
  ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/Piii-thagorus/dotfiles/master/.config/nvim/init.vim
      dest: "/home/{{user_name}}/.config/nvim/init.vim"
  

- name: Vim-airlines
  git: 
    repo: https://github.com/vim-airline/vim-airline.git
    dest: "{{ plugins_dir }}/vim-airline" 


- name: UltiSnips
  git: 
    repo: https://github.com/SirVer/ultisnips.git 
    dest: "{{plugins_dir}}/ultisnips"


- name: Snippets
  git: 
    repo: https://github.com/honza/vim-snippets.git 
    dest: "{{ plugins_dir }}/vim-snippets"


- name: NerdTree
  git: 
    repo: https://github.com/scrooloose/nerdtree 
    dest: "{{ plugins_dir }}/nerdtree"


- name: Tagbar
  git: 
    repo: https://github.com/preservim/tagbar.git
    dest: "{{ plugins_dir }}/tagbar"

